// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwsnptiumwcikdrhkpme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3c25wdGl1bXdjaWtkcmhrcG1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyNzQ1MzAsImV4cCI6MjA2Njg1MDUzMH0.V2IzE5959CM3Wv6Tg6XXMA5gnUloI6K1ag2CmvmeywA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});